routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

## URL
Route::get('/', function () {
    return view('welcome');
});
Route::get('/presentation', function () {
    return view('presentation');
});
Route::get('/article', function () {
    return view('article');
});


## Route
Route::get('/contact', function () {
    return view('contact');
})->name('contact');
Route::get('/autre', function () {
    return view('autre');
})->name('autre');
Route::get('/welcome', function () {
    return view('welcome');
})->name('autre');
Auth::routes();




Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@index')->name('admin_home')->middleware('auth', 'role:Admin');
Route::get('/moderateur', 'ModerateurController@index')->name('moderateur_home')->middleware('auth', 'role:Moderateur');;
Route::get('/autres', 'AutresController@index')->name('autres_home')->middleware('auth', 'role:Autres');
Route::resource('/forum', 'ForumController');

Route::get('/forum/read/{slug}', 'ForumController@show')->name('forumslug');

Route::post('/comment/addComment/{forum}', 'CommentController@addComment')->name('addComment');

Route::post('/comment/replyComment/{comment}', 'CommentController@replyComment')->name('replyComment');

Route::get('/user/{user}', 'ProfilController@index')->name('profile');
Route::get('/user/{user}/edit', 'ProfilController@edit')->name('profile.edit');
Route::patch('/user/{user}', 'ProfilController@update')->name('profile.update');

Route::resource('/tag', 'TagController');

Route::get('/forum/tag/{slug}', 'TagController@index')->name('tagshow');

Route::resource('/chat', 'ChatController');
Route::post('chat/deleteall', 'ChatController@deleteAll')->name('chat_delete_all');

Route::get('/chat/{user}', 'ChatController@index')->name('message');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::ressources('users', 'UserController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Chat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Chat extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'contenu', 'sender_name', 'receiver_name' 
    ];

    public static function countMessageNonLus($user){
        $chat = Chat::where('receiver_name', $user)->get();

        $notif = 0;
        foreach($chat as $chats) {
            if ($chats->check == 0) {
                $notif += 1;
            }
        }

        return $notif;
    }
}

app/Http/Controllers/ChatController.php
<?php

namespace App\Http\Controllers;

use App\Chat;
use App\User;
use Illuminate\Http\Request;
use Auth;
use App\Tag;
use Illuminate\Support\Str;
use DB;
use Storage;

class ChatController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user1 = Auth::user()->name;

        if($request->message){
            $e = $request->request->all();
            $tag = $e['message'];
        } else {
            $tag = "0";
        }

        $chat = Chat::all();
        $chat2 = Chat::where('receiver_name', $user1)->get();
    
        $user = User::all();
        $notif = 0;
        foreach($chat2 as $chats) {
            if ($chats->check == 0) {
                $notif += 1;
            }
        }

        return view('chat.index', compact('chat', 'tag', 'notif'));
    }

    /**
     * Show the form for creating a new resource.
     *@param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user1 = Auth::user()->name;
        $chat = Chat::where('sender_name', $user1);
        $users = User::all();
        $notif = Chat::countMessageNonLus(Auth::user()->name);

        return view('chat.create', compact('chat', 'users', 'user1', 'notif'));

    }




    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'contenu' => 'required',
            'receiver_name' => 'required',
        ]);

        $chat = New Chat;
        $chat->sender_name = Auth::user()->name;
        $chat->title = $request->title;
        $chat->contenu = $request->contenu;
        $chat->receiver_name = $request->receiver_name[0];
        $chat->check = 0;

        $chat->save();
        
        return back()->withInfo('Enregrister avec Succès !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($user)
    {
        $chat = Chat::where('sender_name', $user)->orWhere('receiver_name', $user)->get();
        //$chat = Chat::all();
        $check = 2;
        foreach($chat as $chats) {
            $chats->check = 1;
        }
        $chats->save();
        $notif = Chat::countMessageNonLus(Auth::user()->name);

        return view('chat.show', compact('chat', 'user', 'check', 'notif'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function deleteAll(){
        $chats = Chat::all();
        foreach($chats as $chat) {
            $chat->delete();
        }

        return back();
    }
}

resources/views/chat/create.blade.php
@extends('layouts.app')
@section('title','Creer un tag')
@section('content')
<div class="container animated fadeInRight">
     <div class="jumbotron" id="tc_jumbotron">
        <div class="col-md-8 offset-md-2">
          <div class="text-center"><h3 style="color: #fff;">Envoyer un Message</h3></div><hr style="background: #fff"> 
        </div>
      <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card"> 
                <div class="card-body">
                   <form action="{{route('chat.store')}}" method="post">
                      {{csrf_field()}}
                      
                    <div class="form-group">
                        <input disabled="disabled" id="tc_input" type="text" class="form-control" value="{{$user1}}" name="sender_name">
                    </div>
                    <div class="form-group">
                      <input type="text" id="tc_input" class="form-control" name="title" placeholder="Titre.."> 
                    </div>
                    <div class="form-group">
                      <input type="text" id="tc_input" class="form-control" name="contenu" placeholder="Contenu.."> 
                    </div>
                    <div class="form-group">
                    <select name="receiver_name[]" multiple="multiple"  id="tc_input" class="form-control receiver_name">
                        @foreach($users as $user)
                          <option value="{{$user->name}}">{{$user->name}}</option>
                        @endforeach
                    </select>
                    </div>  
                    <div class="card">
                      <div class="card-body">   
                        <button style="background-color:black" type="submit" class="btn btn-success btn-block">Enregistrer</button>
                      </div>
                    </div>
               </form>
               </div>
               </div>
<br>

                  </div>
              </div>
        </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/chat/index.blade.php
@extends('layouts.app')
@section('title','Tags')
@section('content')
<?php 
$iPod    = stripos($_SERVER['HTTP_USER_AGENT'],"iPod");
$iPhone  = stripos($_SERVER['HTTP_USER_AGENT'],"iPhone");
$iPad    = stripos($_SERVER['HTTP_USER_AGENT'],"iPad");
$Android = stripos($_SERVER['HTTP_USER_AGENT'],"Android");
$webOS   = stripos($_SERVER['HTTP_USER_AGENT'],"webOS");
?>
<div style="z-index: 0" class="container animated fadeInDown">
  <div class="jumbotron" id="tc_jumbotron">
    <div class="card-body"style="color: #fff;border:1px solid #fff;">
        <div class="text-center">
           <h1 style="font-size: 3.5rem;">Chats</h1> 
          <p>Communiquer avec tous les utilisateurs</p> 
      </div>
    </div>
  </div>
</div>  
<div class="container animated fadeInRight">
    <div class="row">
        <div class="col-md-12" id="tc_container_wrap">
            <div class="card">
                <div class="card-body" style="background: #f9f9f9;"> 
                    <div class="card">
                       <div class="card-header" style="background-color: #556080;padding: 6px 11px 6px 23px;">
                          <div class="menu_a" style="float: left;">
                          <a href="{{route('chat.index')}}">Message</a> 
                          </div>
                          <div class="search" style="margin: 3px;">
                          <div class="col-md-4 float-right" style="padding-right: 0;">
                          <div class="input-group">
                          <input type="text" class="form-control" placeholder="Chercher un message..." style=" margin-right: 3px;background: #f5f8fa;">
                          <span class="input-group-btn">
                          <button class="btn btn-warning" type="button" style="color: #fff;" >Go!</button>
                        </span>
                        </div>
                       </div>
                     </div>
                    </div>
                  </div>  
      <br>
      @if($iPhone || $iPod || $iPad || $Android)
            <div style="margin-top: -20px" class="col-md-4"> <br>
               <div class="card">
                <div class="card-header" style="background: #9F9F9F; color: #fff; padding: 8px 1.25rem;">Conversation</div>
                <div class="list-group">

                 <a href="{{ route('chat.index', ['message'=> '1' ]) }}"  class="list-group-item <?= $tag === '1' ? 'active' : ''  ?> " id="index_hover">Message envoyé(s)
                </a>
                <a href="{{ route('chat.index', ['message'=> '2']) }}"  class="list-group-item <?= $tag === '2' ? 'active' : ''  ?> " id="index_hover">Message reçu(s)
                </a> 
                <a href="{{ route('chat.index', ['message'=> '3' ]) }}"  class="list-group-item <?= $tag === '3' ? 'active' : ''  ?> " id="index_hover">Tous les envoyé(s)
                </a> 

                </div>
                </div>
                </div>
                <br>
                @else
                @endif
<div class="row" style="margin-top: 50px">
<div class="col-md-12" id="tc_container_wrap">
            <div class="card" id="tc_paneldefault"> 
                <div class="card-body" id="tc_panelbody"  style="background: #f9f9f9;">  
                    <a href="{{route('chat.create')}}" class="btn btn-success btn-block">Nouveau Chat</a>
                    <a class="btn btn-danger btn-block" style="background-color: #FA9494" href="{{ route('chat_delete_all') }}"
                        onclick="event.preventDefault();
                                      document.getElementById('destroy-chat').submit();" style="color: #444;">
                        {{ __('Supprimer') }}
                    </a>
                    <form id="destroy-chat" action="{{ route('chat_delete_all') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
               <div class="row">
               @if($iPhone || $iPod || $iPad || $Android)
               <div class="col-md-8"><br>
               @else
               <div class="col-md-8" style="    padding-right: 0;"><br>
               @endif
                <table class="table table-bordered">
              <thead id="tc_thead">
                <tr>
                  <th scope="col">Derniere(s) Message(s)</th>
                  <th scope="col">Utilisateur</th>

                </tr>
              </thead>
              <tbody style="background: #f9f9f9;">
              @foreach($chat as $chats)
              @if ($chats->sender_name == Auth::user()->name && $chats->receiver_name !== Auth::user()->name)
              @if($tag == '1' || $tag == '3' || $tag == '0')
                <tr> 
                <td width="453">
                <div class="forum_title">
                <h4> <a href="{{route('chat.show', $chats->receiver_name)}}">{{$chats->title}}</a></h4>
                <p> {{$chats->contenu}}</p> 
              </td>
              <td>
            <div class="forum_by">
            <small style="margin-bottom: 0; color: #666">{{$chats->created_at}}</small><br>
            <small style="margin-bottom: 0; color: #666">Vous avez envoyez ce message à : <a href="">{{$chats->receiver_name}}</a></small>
             
             @endif
             @elseif ($chats->receiver_name == Auth::user()->name && $chats->sender_name !== Auth::user()->name )

            @if ($tag == '3' || $tag == '2' || $tag == '0')
               <tr> 
                <td width="453">
                <div class="forum_title">
                <h4> <a href="{{route('chat.show', $chats->sender_name)}}">{{$chats->title}}</a></h4>
                <p> {{$chats->contenu}}</p>
                @if ($chats->check == 0)
                  <i class="fa fa-envelope" aria-hidden="true"></i>
                @endif
              </td>
              <td>
            <div class="forum_by">
            <small style="margin-bottom: 0; color: #666">{{$chats->created_at}}</small><br>
            <small style="margin-bottom: 0; color: #666">Vous avez reçu un message de : <a href="">{{$chats->sender_name}}</a></small>             
             @endif
             
             
             
             @endif
             @endforeach
            </div>
            </td>
            </tr>
                <?php  ?>

              </tbody>
              
            </table>
            </div>
            @if($iPhone || $iPod || $iPad || $Android)
            @else
            <div class="col-md-4"> <br>
               <div class="card">
                <div class="card-header" style="background: #9F9F9F; color: #fff; padding: 8px 1.25rem;">Conversation</div>
                <div class="list-group">

                 <a href="{{ route('chat.index', ['message'=> '1' ]) }}"  class="list-group-item <?= $tag === '1' ? 'active' : ''  ?> " id="index_hover">Message envoyé(s)
                </a>
                <a href="{{ route('chat.index', ['message'=> '2']) }}"  class="list-group-item <?= $tag === '2' ? 'active' : ''  ?> " id="index_hover">Message reçu(s)
                </a> 
                <a href="{{ route('chat.index', ['message'=> '3' ]) }}"  class="list-group-item <?= $tag === '3' ? 'active' : ''  ?> " id="index_hover">Tous les envoyé(s)
                </a> 

                </div>
                </div>
                </div>
                @endif
                </div>


                <hr style="margin-top: 0;"> 
                <div class="card">
                <div class="card-header"></div>
                <div class="card-body" style="background: rgb(90, 90, 90)"></div>
                <div class="card-header"></div>
                </div>
            </div>
            

    </div>


      </div>
    </div>
 <br>
@endsection
 

resources/views/chat/show.blade.php
@extends('layouts.app')
@section('title','Tags')
@section('content')
<div class="container">
  <div class="jumbotron" id="tc_jumbotron">
    <div class="card-body"style="color: #fff;border:1px solid #fff;">
        <div class="text-center">
           <h1 style="font-size: 3.5rem;">Chats</h1> 
          <p>Communiquer avec tous les utilisateurs</p> 
      </div>
    </div>
  </div>
</div>  
<div class="container">
    <div class="row">
        <div class="col-md-12" id="tc_container_wrap">
            <div class="card">
                <div class="card-body" style="background: #f9f9f9;"> 
                    <div class="card">
                       <div class="card-header" style="background-color: #2ab27b;padding: 6px 11px 6px 23px;">
                          <div class="menu_a" style="float: left;">
                          <a href="{{route('chat.index')}}">Message</a> 
                          </div>
                          <div class="search" style="margin: 3px;">
                          <div class="col-md-4 float-right" style="padding-right: 0;">
                          <div class="input-group">
                          <input type="text" class="form-control" placeholder="Chercher un message..." style=" margin-right: 3px;background: #f5f8fa;">
                          <span class="input-group-btn">
                          <button class="btn btn-warning" type="button" style="color: #fff;" >Go!</button>
                        </span>
                        </div>
                       </div>
                     </div>
                    </div>
                  </div>  
      <br>
<div class="row" style="margin-top: 50px">
<div class="col-md-12" id="tc_container_wrap">
            <div class="card" id="tc_paneldefault"> 
                <div class="card-body" id="tc_panelbody"  style="background: #f9f9f9;">  
                    <a href="{{route('chat.create')}}" class="btn btn-success btn-block">Nouveau Chat</a>
               <div class="row">

               <div class="col-md-12" style="    padding-right: 0;"><br>
                <table style="width: 98.5%;" class="table table-bordered">
              <thead id="tc_thead">
                <tr>
                  <th scope="col">Derniere(s) Message(s)</th>

                </tr>
              </thead>
              <tbody style="background: #f9f9f9;">
              @foreach($chat as $chats)
              @if ($chats->sender_name == $user || $chats->receiver_name == $user)
              @if ($chats->sender_name == Auth::user()->name && $chats->receiver_name !== Auth::user()->name)
                <tr> 
                <td width="100%">
                <div style="float: right; margin-right: 5%" class="forum_title">
                <h4> <a href="{{route('chat.show', $chats->sender_name)}}">{{$chats->title}}</a></h4>
                <p style="color: black;"> {{$chats->contenu}}</p> 
                <small style="margin-bottom: 0; color: #666">{{$chats->created_at}}</small><br>
            <small style="margin-bottom: 0; color: #666">Vous avez envoyez ce message à : <a href="">{{$chats->receiver_name}}</a></small>
     


             @elseif ($chats->receiver_name == Auth::user()->name && $chats->sender_name !== Auth::user()->name )

               <tr> 
                <td width="453">
                <div style="float: left; margin-left: 5%" class="forum_title">
                <h4> <a href="{{route('chat.show', $chats->sender_name)}}">{{$chats->title}}</a></h4>
                <p style="color: black;"> {{$chats->contenu}}</p> 

            <small style="margin-bottom: 0; color: #666">{{$chats->created_at}}</small><br>
            <small style="margin-bottom: 0; color: #666">Vous avez reçu un message de : <a href="">{{$chats->sender_name}}</a></small>  
              </td>

          

             
             
             
             @endif
             @endif
             @endforeach
            </div>
            </td>
            </tr>
                <?php  ?>

              </tbody>
              
            </table>
            </div>

            

    </div>


      </div>
    </div>
 <br>
@endsection
 