routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

## URL
Route::get('/', function () {
    return view('welcome');
});
Route::get('/presentation', function () {
    return view('presentation');
});
Route::get('/article', function () {
    return view('article');
});


## Route
Route::get('/contact', function () {
    return view('contact');
})->name('contact');
Route::get('/autre', function () {
    return view('autre');
})->name('autre');
Route::get('/welcome', function () {
    return view('welcome');
})->name('autre');
Auth::routes();




Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@index')->name('admin_home')->middleware('auth', 'role:Admin');
Route::get('/moderateur', 'ModerateurController@index')->name('moderateur_home')->middleware('auth', 'role:Moderateur');;
Route::get('/autres', 'AutresController@index')->name('autres_home')->middleware('auth', 'role:Autres');
Route::resource('/forum', 'ForumController');

Route::get('/forum/read/{slug}', 'ForumController@show')->name('forumslug');

Route::post('/comment/addComment/{forum}', 'CommentController@addComment')->name('addComment');

Route::post('/comment/replyComment/{comment}', 'CommentController@replyComment')->name('replyComment');

Route::get('/user/{user}', 'ProfilController@index')->name('profile');
Route::get('/user/{user}/edit', 'ProfilController@edit')->name('profile.edit');
Route::patch('/user/{user}', 'ProfilController@update')->name('profile.update');

Route::resource('/tag', 'TagController');

Route::get('/forum/tag/{slug}', 'TagController@index')->name('tagshow');

Route::resource('/chat', 'ChatController');
Route::post('chat/deleteall', 'ChatController@deleteAll')->name('chat_delete_all');

Route::get('/chat/{user}', 'ChatController@index')->name('message');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::ressources('users', 'UserController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/forum.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Overtrue\LaravelLike\Traits\CanBeLiked;

class forum extends Model
{

    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    public function hasTag($tagName) 
    {
        foreach ($this->tags as $tag) {
            if ($tag->name === $tagName) {
                return true;
            }
        }
        return false;
    }
}

app/Http/Controllers/ForumController.php
<?php

namespace App\Http\Controllers;

use App\forum;
use Illuminate\Http\Request;
use Auth;
use App\Tag;
use Illuminate\Support\Str;
use DB;
use Storage;
use App\Chat;
use Illuminate\Database\Eloquent\Model;
use Overtrue\LaravelLike\Traits\CanBeLiked;
use App\User;

class ForumController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except('index', 'show');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index(Request $request)
    {

        $tags = Tag::all();
        $tagName = null;
        if($request->tag){
            $e = $request->request->all();
            $tagName = $e['tag'];
            $forums = Forum::all();

            $forums = $this->filterByTag($forums, $tagName);
        } else{
            $forums = Forum::paginate(5);
        }

        return view('forum.index', compact('forums', 'tags', 'tagName'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $forums = Forum::orderBy('id', 'desc')->paginate(1);
        $tags = Tag::all();
        $notif = Chat::countMessageNonLus(Auth::user()->name);
        return view('forum.create', compact('tags', 'forums', 'notif'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'image' => 'image|mimes:jpg,jpeg,png,gif|max:1024',
        ]);

        $forums = New Forum;
        $forums->user_id = Auth::user()->id;
        $forums->title = $request->title;
        $forums->slug = str::slug($request->title);
        $forums->description = $request->description;
        if ($request->file('image')) {
            $file = $request->file('image');
            $filename = time().'.'.$file->getClientOriginalExtension();
            $location = public_path('/images');
            $file->move($location, $filename);
            $forums->image = $filename;
        }
        $forums->save();
        $forums->tags()->sync($request->tags);

        return back()->withInfo('Enregrister avec Succès !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $forums = Forum::where('id', $slug)
                        ->orWhere('slug', $slug)
                        ->firstOrFail();
        return view('forum.show', compact('forums'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $tags = Tag::all();
        $forum = Forum::where('id', $slug)
                        ->orWhere('slug', $slug)
                        ->firstOrFail();
        return view('forum.edit', compact('forum', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'tags' => 'required',
            'image' => 'image|mimes:jpg,jpeg,png,gif|max:1024',
        ]);
        
        $forums = Forum::find($id);
        $forums->user_id = $id;
        $forums->title = $request->title;
        $forums->slug = str::slug($request->title);
        $forums->description = $request->description;
        if ($request->file('image')) {
            $file = $request->file('image');
            $filename = time().''.$file->getClientOriginalExtension();
            $location = public_path('/images');
            $file->move($location, $filename);

            $oldImage = $forums->image;
            \Storage::delete($oldImage);
            $forums->image = $filename;
        }
        $forums->save();
        $forums->tags()->sync($request->tags);

        return back()->withInfo('Mise à jour effectuée avec Succès !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $forum = Forum::find($id);
        Storage::delete($forum->image);
        $forum->tags()->detach();
        $forum->delete();

        return back()->withInfo('Article supprimé !');
    }

    private function filterByTag($forums, string $tagName): array
    {
        $result = [];
        foreach ($forums as $forum) {
            if ($forum->hasTag($tagName)) {
                $result[] = $forum;
            }
        }
        return $result;
    }
}

resources/views/forum/create.blade.php
@extends('layouts.app')
@section('title','Buat Pertanyaan')
@section('content')
<div class="container animated fadeInDown">
     <div class="jumbotron" id="tc_jumbotron">
        <div class="col-md-8 offset-md-2">
          <div class="text-center"><h3 style="color: #fff;">Creer un article</h3></div><hr style="background: #fff"> 
        </div>
      <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card"> 
                <div class="card-body">
                   <form action="{{route('forum.store')}}" method="post"  enctype="multipart/form-data">
                      {{csrf_field()}}
                    <div class="form-group">
                      <input type="text" id="tc_input" class="form-control" name="title" placeholder="Title"> 
                    </div>
                    
                   <div class="des"> 
                 <a class="btn btn_tc btn-block" data-toggle="collapse" data-target="#description-textarea" style="color: #777">Description</a> 
              <div id="description-textarea" class="collapse">     
                <div class="bg">
                   <div class="form-group">
                      <textarea name="description" id="editor">

                      </textarea>
                    </div>
                </div> 
              </div>             
            </div>
               <div class="form-group">
                <select name="tags[]" multiple="multiple" id="tc_input" class="form-control tags" id="">
                        @foreach($tags as $tag)
                         <option value="{{$tag->id}}">{{$tag->name}}</option>
                         @endforeach
                       </select>
                    </div>
             
             <a data-toggle="collapse" data-target="#screenshot-open"><i class="fa fa-image" id="upload_image"></i></a>
            <div id="screenshot-open" class="collapse">  
              <div class="bg">
                 <div class="form-group">
                     <input type="file" class="form-control" name="image" placeholder="image" style="background-color: #f5f8fa;"> 
                  </div>
              </div> 
            </div>
             <br> 
            
             <button style="background-color:black" type="submit" class="btn btn-success btn-block">Enregistrer</button>
               </form>
              </div>
              </div>
           <br>

          <div class="create_info" style="color: #fff;">
            <h5><i class="fa fa-info-circle"></i> Info</h5>
            <span>- Entrer <strong>tous</strong> les champs pour creer un article.</span> 
          </div><br>
          <div class="alert alert-info alert-dismissible fade show" role="alert">
          @forelse($forums as $forum)
          <b>Voici le nom du dernier article cree :</b><br>

           <a href="{{route('forumslug', $forum->slug)}}" style="color: #444"><h5 style="margin-top: 4px;"><i class="fa fa-newspaper-o"></i> {{$forum->title}}</h5></a> 
           @empty
        <strong> Pertanyaan baru akan muncul disini.</strong><br> 
          @endforelse
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
            </div>
        </div>
    </div>
</div>
@endsection
 
@section('js')
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<script src="ckeditor.js"></script>
<script src="{{ asset('js/ckeditor.js') }}"></script>
<script type="text/javascript">
    $(".tags").select2({
        placeholder: "Select tags",
        maximumSelectionLength: 2
    });

</script>

<script>

	ClassicEditor
		.create( document.querySelector( '#editor' ), {
			// toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
		} )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( err => {
			console.error( err.stack );
		} );
</script>
<script src="[ckeditor-build-path]/ckeditor.js"></script>

<script src="https://cdn.ckeditor.com/ckeditor5/15.0.0/classic/ckeditor.js"></script>

@endsection

resources/views/forum/edit.blade.php
@extends('layouts.app')
@section('title',"Edit : $forum->title")
@section('content')
<div class="container animated fadeInDown">
    <div class="jumbotron" id="tc_jumbotron">
      <div class="col-md-8 offset-md-2">
        <div class="text-center"><h3 style="color: #fff;">Modifier l'Article</h3></div><hr style="background: #fff"> 
      </div>
    <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card">
                <div class="card-body">
                  <form action="{{route('forum.update', $forum->id)}}" method="post" enctype="multipart/form-data">
                    {{csrf_field()}}
                    {{method_field('PUT')}}
                  <div class="form-group">
                      <input type="text" name="title" class="form-control" value="{{$forum->title}}">
                  </div>
                  <div class="form-group">
                    <textarea name="description" id="editor">
                      {{$forum->description}}
                    </textarea>
                  </div> 
                  <div class="form-group">
                    <select name="tags[]" multiple="multiple" class="form-control tags">
                        @foreach($tags as $tag)
                          <option value="{{$tag->id}}">{{$tag->name}}</option>
                        @endforeach
                    </select>
                  </div>      
                  <a data-toggle="collapse" data-target="#edit_image"><i class="fa fa-image" id="upload_image"></i></a>
                    <div id="edit_image" class="collapse">  
                        <div class="bg">
                            <div class="form-group">
                              <input type="file" class="form-control" name="image" placeholder="image" style="background-color: #f5f8fa;"> 
                            </div>
                            </div>  
                            @if (empty($forums->image))
                              <small><i class="fa fa-info-circle"></i>Veuillez à choisir une image</small>
                            @else
                            <div class="form-group">
                               <div class="col-md-4"> 
                               <img src="{{asset('images/'.$forum->image)}}" alt="" width="100%">
                               </div>
                           </div>
                           @endif
                          </div>
                           <br> 
                      <button style="background-color:black" type="submit" class="btn btn-success btn-block">Submit</button>
                   </form>
                </div>
            </div>
          <br> 
        <div class="create_info" style="color: #fff;">
         <h5><i class="fa fa-info-circle"></i> Info</h5>
           <span>- Klik icon <strong>Gambar</strong> untuk upload dan edit gambar screenshot.</span> 
          </div><br>
          <div class="alert alert-info alert-dismissible fade show" role="alert"> 
          <b>Pertanyaan terakhir edit:</b><br> 
           <a href="#" style="color: #444"><h5 style="margin-top: 4px;"><i class="fa fa-newspaper-o"></i> {{$forum->title}}</h5></a>  
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
       </div>
    </div>
  </div>
</div>
@endsection
  
 @section('js')
 <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
 <script src="{{ asset('js/ckeditor.js') }}"></script>
<script type="text/javascript">
$(".tags").select2().val({!! json_encode($forum->tags()->allRelatedIds() ) !!}).trigger('change');
</script>

<script>
	ClassicEditor
		.create( document.querySelector( '#editor' ), {
			// toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
		} )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( err => {
			console.error( err.stack );
		} );
</script>
<script src="[ckeditor-build-path]/ckeditor.js"></script>
@endsection

resources/views/forum/index.blade.php
@extends('layouts.app')
@section('title','Forum')
@section('content')
<?php 
$iPod    = stripos($_SERVER['HTTP_USER_AGENT'],"iPod");
$iPhone  = stripos($_SERVER['HTTP_USER_AGENT'],"iPhone");
$iPad    = stripos($_SERVER['HTTP_USER_AGENT'],"iPad");
$Android = stripos($_SERVER['HTTP_USER_AGENT'],"Android");
$webOS   = stripos($_SERVER['HTTP_USER_AGENT'],"webOS");
?>

<div class="container animated fadeInLeft">
  <div class="jumbotron" id="tc_jumbotron">
    <div class="card-body" id="xx" style="color: #fff;     border:1px solid #fff;">
        <div class="text-center"> 
           <h1 style="    font-size: 3.5rem;">FORUM</h1> 
        <p></p>  
          </div>
        </div> 
      </div> 
    </div>
    @if($iPhone || $iPod || $iPad || $Android)
    
                <div class="card-body" id="tc_panelbody"  style="background: #f9f9f9; margin-left: -20px;">  
               <div class="row">
               <div class="col-md-8" style="    padding-right: 0;">

               <div class="col-md-4">
               @if($iPhone || $iPod || $iPad || $Android)
               @else
               <br>
               @endif
                <a href="{{route('forum.create')}}" class="btn btn-success btn-block">Creer un Article</a><br>
               <div class="card" style="margin-bottom: 100px">
                <div class="card-header" style="background: #9F9F9F; color: #fff; padding: 8px 1.25rem;">Categorie(s)</div>
                <div class="list-group">
                <?php $res = []; ?>
                @foreach($tags as $tag)
                 <a href="{{ route('forum.index', ['tag'=> $tag->name ]) }}"  class="list-group-item <?= $tag->name === $tagName ? 'active' : ''  ?>" id="index_hover">{{$tag->name}}
                </a> 
                @endforeach
                <a href="{{ route('forum.index') }}"  class="list-group-item <?= $tag->name === "" ? 'active' : ''  ?>" id="index_hover">Toutes les catégories
                </a> 
                </div>
                </div>
                </div>
            @else
            @endif


            @if ($iPhone || $iPod || $iPad || $Android)
            <div style="margin-top: -70px" class="container animated fadeInRight"> 
              @else
              <div class="container animated fadeInRight"> 
              <div class="row">
             <div class="col-md-12" id="tc_container_wrap">
            @endif
            <div class="card" id="tc_paneldefault"> 
                <div class="card-body" id="tc_panelbody"  style="background: #f9f9f9;">  
               <div class="row">
               @if ($iPhone || $iPod || $iPad || $Android)
              @else
              <div class="col-md-8" style="    padding-right: 0;"><br>
               @endif
                <table class="table table-bordered">
              <thead id="tc_thead">
                <tr>
                  <th scope="col">Article</th>
                  <th scope="col">Commentaires</th>
                  <th scope="col">Utilisateur</th>
                </tr>
              </thead>
              <tbody style="background: #f9f9f9;">
                @foreach($forums as $forum)
                <tr> 
                <td width="553">
                <div class="forum_title">
                <h4> <a href="{{route('forumslug', $forum->slug)}}">{{ Str::limit($forum->title, 45)}}</a></h4>
                <p>  {!!  strip_tags( Str::limit($forum->description, 60) )!!}</p> 
                <div>
                @if (empty($forum->image))
                  <div style="margin-left: -20px">
                  @foreach($forum->tags as $tag)
                    <div style="margin-left: 4%">
                      <a href="{{ route('forum.index', ['tag'=> $tag->name ]) }}" style="background-color: grey; top: initial; right: auto" class="badge badge-success tag_label">{{$tag->name}}</a>
                    <div>
                  @endforeach
                  <div>
                @else
                  <div style="background-color: grey; top: initial;right: auto" class="badge badge-success tag_label_image"><i class="fa fa-image"></i></div> 
                  @foreach($forum->tags as $tag)
                    <div style="margin-left: 4%">
                      <a href="{{ route('forum.index', ['tag'=> $tag->name ]) }}" style="background-color: grey; top: initial; margin-left: 10px; right:auto" class="badge badge-success tag_label">{{$tag->name}}</a>
                    <div>
                  @endforeach
                @endif
                </div>

                </div> </div>
              </td>
              <td style="text-align: center"><small> {{$forum->comments->count()}}</small></td>
              <td>
            <div class="forum_by">
            <small style="margin-bottom: 0; color: #666">{{$forum->created_at}}</small>
            <small>by <a href="{{ route('profile', $forum->user->name ) }}">{{ $forum->user->name }}</a></small>
            @if ($forum->user->image !== null)<br>
            <img src="{{asset('images/' .$forum->user->image)}}" style="background: #fff; width: 35%; border-radius: 50%; height: 50%;">
            @endif     
            </div>
            </td>
            </tr>
                <?php  ?>
                @endforeach
              </tbody>
            </table>
            @if ($iPhone || $iPod || $iPad || $Android)
              @else
              </div>
            @endif
              @if ($iPhone || $iPod || $iPad || $Android)
              @else
                <div class="col-md-4"> <br>
                <a href="{{route('forum.create')}}" class="btn btn-success btn-block">Creer un Article</a><br>
               <div class="card" style="margin-bottom: 100px">
                <div class="card-header" style="background: #9F9F9F; color: #fff; padding: 8px 1.25rem;">Categorie(s)</div>
                <div class="list-group">
                <?php $res = []; ?>
                @if ($tags->isEmpty())
                @else
            
                  @foreach($tags as $tag)
                  <a href="{{ route('forum.index', ['tag'=> $tag->name ]) }}"  class="list-group-item <?= $tag->name === $tagName ? 'active' : ''  ?>" id="index_hover">{{$tag->name}}
                  </a> 
                  @endforeach
                  <a href="{{ route('forum.index') }}"  class="list-group-item <?= $tag->name === "" ? 'active' : ''  ?>" id="index_hover">Toutes les catégories
                  </a>
                @endif
                </div>
                </div>
                </div>
              @endif
                </div>
                <hr style="margin-top: 0;"> 
                <div class="card">
                <div class="card-header"></div>
                <div class="card-body" style="background: rgb(90, 90, 90)"></div>
                <div class="card-header"></div>
                </div>
            </div>
          </div>
        </div>
    </div>
</div><br><br>

@endsection
 