routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

## URL
Route::get('/', function () {
    return view('welcome');
});
Route::get('/presentation', function () {
    return view('presentation');
});
Route::get('/article', function () {
    return view('article');
});


## Route
Route::get('/contact', function () {
    return view('contact');
})->name('contact');
Route::get('/autre', function () {
    return view('autre');
})->name('autre');
Route::get('/welcome', function () {
    return view('welcome');
})->name('autre');
Auth::routes();




Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@index')->name('admin_home')->middleware('auth', 'role:Admin');
Route::get('/moderateur', 'ModerateurController@index')->name('moderateur_home')->middleware('auth', 'role:Moderateur');;
Route::get('/autres', 'AutresController@index')->name('autres_home')->middleware('auth', 'role:Autres');
Route::resource('/forum', 'ForumController');

Route::get('/forum/read/{slug}', 'ForumController@show')->name('forumslug');

Route::post('/comment/addComment/{forum}', 'CommentController@addComment')->name('addComment');

Route::post('/comment/replyComment/{comment}', 'CommentController@replyComment')->name('replyComment');

Route::get('/user/{user}', 'ProfilController@index')->name('profile');
Route::get('/user/{user}/edit', 'ProfilController@edit')->name('profile.edit');
Route::patch('/user/{user}', 'ProfilController@update')->name('profile.update');

Route::resource('/tag', 'TagController');

Route::get('/forum/tag/{slug}', 'TagController@index')->name('tagshow');

Route::resource('/chat', 'ChatController');
Route::post('chat/deleteall', 'ChatController@deleteAll')->name('chat_delete_all');

Route::get('/chat/{user}', 'ChatController@index')->name('message');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::ressources('users', 'UserController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'slug'
    ];
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Tag;
use App\Chat;
use Auth;
use DB;

class TagController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();

        $notif = Chat::countMessageNonLus(Auth::user()->name);
        return view('tag.index', compact('tags', 'notif'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();
        $notif = Chat::countMessageNonLus(Auth::user()->name);
        return view('tag.create', compact('tags', 'notif'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tag = New Tag;
        $tag->name = $request->name;
        $tag->slug = Str::slug($request->name);
        $tag->save();

        return back()->withInfo('Le Tag à été créé !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        //$populars = DB::table('forums')
        //               ->join('page-views', 'forums.id', '=', 'page-views.visitable_id')
        //                 ->select(DB::raw('count(visitable_id) as count'), 'forums.id', 'forums.title', 'forums.slug')
        //                 ->groupBy('id', 'title', 'slug')
        //             ->orderBy('count', 'desc')
        //                 ->take(5)
        //                 ->get();


        $tags = Tag::where('id', $slug)
                        ->orWhere('slug', $slug)
                        ->firstOrFail();
                        
        return view('tag.show', compact('tags'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);
        return view('tag.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::find($id);
        $tag->name = $request->name;
        $tag->slug = Str::slug($request->name);
        $tag->save();

        return redirect()->route('tag.create')->withInfo('Le Tag à été mis à jour !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);
        $tag->delete();
    
        return redirect()->route('tag.create')->withInfo('Le Tag à été supprimé !');
    }
}

resources/views/tag/create.blade.php
@extends('layouts.app')
@section('title','Creer un tag')
@section('content')
<div class="container animated fadeInRight">
     <div class="jumbotron" id="tc_jumbotron">
        <div class="col-md-8 offset-md-2">
          <div class="text-center"><h3 style="color: #fff;">Creer un tag</h3></div><hr style="background: #fff"> 
        </div>
      <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card"> 
                <div class="card-body">
                   <form action="{{route('tag.store')}}" method="post">
                      {{csrf_field()}}
                    <div class="form-group">
                      <input type="text" id="tc_input" class="form-control" name="name" placeholder="Nom.."> 
                    </div>


             <button style="background-color:black" type="submit" class="btn btn-success btn-block">Enregistrer</button>
               </form>
               </div>
               </div>
<br>
    <div class="card">
        <div class="card-body">   
            <table class="table table-bordered"> 
            <tbody>   
            @foreach($tags as $tag)
               <tr>
               <td>{{$tag->name}}</td>
               
                <td width="10"><a href="{{route('tag.edit', $tag->id)}}" class="btn btn-sm btn-success"><i class="fa fa-edit"></i> Edit</a></td>
                <td width="10"> 
                <form action="{{route('tag.destroy', $tag->id)}}" method="post" style="margin: 0;">
                 {{csrf_field()}}
                  {{method_field('DELETE')}}
                  <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Delete</button>
                 </form> 
                </td>
              </tr>
                @endforeach
              </tbody>
                  </table>
                </div>
            </div>
                  </div>
              </div>
        </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tag/edit.blade.php
@extends('layouts.app')
@section('title',"Editer Tag: $tag->name")
@section('content')
<div class="container animated fadeInRight">
     <div class="jumbotron" id="tc_jumbotron">
        <div class="col-md-8 offset-md-2">
          <div class="text-center"><h3 style="color: #fff;">Editer le Tag: {{$tag->name}}</h3></div><hr style="background: #fff"> 
        </div>
      <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card"> 
                <div class="card-body">
                   <form action="{{route('tag.update', $tag->id)}}" method="post">
                      {{csrf_field()}}
                        {{method_field('PUT')}}
                    <div class="form-group">
                      <input type="text" id="tc_input" class="form-control" name="name" value="{{$tag->name}}"> 
                    </div>


             <button style="background-color:black" type="submit" class="btn btn-success btn-block">Enregistrer</button>
               </form>
               </div>
               </div>
<br>

                  </div>
              </div>
        </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tag/index.blade.php
@extends('layouts.app')
@section('title','Tags')
@section('content')
<div class="container animated fadeInDown">
  <div class="jumbotron" id="tc_jumbotron">
    <div class="card-body"style="color: #fff;border:1px solid #fff;">
        <div class="text-center">
           <h1 style="font-size: 3.5rem;">Tags</h1> 
      </div>
    </div>
  </div>
</div>  
<div class="container animated fadeInRight">

    <div class="row">
        <div class="col-md-12" id="tc_container_wrap">
            <div class="card">
            <a style="margin:25px; width: 95%" href="{{route('tag.create')}}" class="btn btn-success btn-block">Créer un Tag</a><br>
      <br>

<div class="row">
   <div class="col-md-12">
     @foreach($tags as $tag)
       <a style="margin-right: 2%; margin-left: 2%; margin-bottom: 2%; width: 20%" href="{{ route('forum.index', ['tag'=> $tag->name ]) }}" class="btn btn-success btn-sm">{{$tag->name}}</a>
     @endforeach
    </div>
       <div class="col-md-4">
           </div>
           </div><br><br>
            <div class="card">
              <div class="card-header"></div>
               <div class="card-body" style="background: rgb(90, 90, 90)"></div>
              <div class="card-header"></div>
             </div>
            </div>
           </div>
         </div>
      </div>
    </div>
 <br>
 </div>  
@endsection
 

resources/views/tag/show.blade.php
@extends('layouts.app')
@section('title',"$tags->name tag")
@section('content')
<div class="container animated fadeInRight">
  <div class="jumbotron" id="tc_jumbotron">
    <div class="card-body" id="xx" style="color: #fff;border:1px solid #fff;">
        <div class="text-center">
        <small>Tag:</small>
           <h1 style="font-size: 3.5rem;">{{$tags->name}}</h1>
      </div>
    </div>
  </div>
</div>  
<div class="container">
    <div class="row">
        <div class="col-md-12" id="tc_container_wrap">
            <div class="card" id="tc_paneldefault">
         <div class="card-body" id="tc_panelbody"  style="background: #f9f9f9;"> 
             <div class="card">
                       <div class="card-header" style="background-color: #2ab27b;padding: 6px 11px 6px 23px;">
                          <div class="menu_a" style="float: left;">
                          <a href="{{route('tag.index')}}">Tag</a> 
                          </div>
                          <div class="search" style="margin: 3px;">
                          <div class="col-md-4 float-right" style="    padding-right: 0;">
                          <div class="input-group">
                          <input type="text" class="form-control" placeholder="Search for..." style=" margin-right: 3px;background: #f5f8fa;">
                          <span class="input-group-btn">
                          <button class="btn btn-warning" type="button" style="color: #fff;" >Go!</button>
                        </span>
                        </div>
                       </div>
                     </div>
                    </div>
                  </div>  
          <div class="row">
            <div class="col-md-8" style="padding-right: 0;"><br>
           <table class="table table-bordered">
          <thead id="tc_thead">
            <tr>
              <th scope="col">Thread</th>
              <th scope="col">Comments</th>
              <th scope="col">Views</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody style="background: #f9f9f9;">
          @foreach($errors->tags as $forum)
            <tr>
             <td width="453">
         <div class="forum_title">
                <h4> <a href="{{route('forumslug', $forum->slug)}}">{{ str_limit($forum->title, 45) }}</a></h4>
                <p>{!! strip_tags(str_limit($forum->description, 60) ) !!}</p>
                @foreach($forum->tags as $tag)
                <a href="{{route('tag.show', $tag->name)}}" class="badge badge-success tag_label">#{{$tag->name}}</a>
                @endforeach
                 @if (empty($forum->image)) 
                @else
              <div class="badge badge-success tag_label_image"><i class="fa fa-image"></i></div>
               @endif
               </div>
               </td>
              <td style="text-align: center"><small> {{$forum->getPageViews()}}</small></td>
              <td>
                <div class="forum_by">
                <small style="margin-bottom: 0; color: #666">{{$forum->created_at->diffForHumans()}}</small>
                 <small>by <a href="#">{{$forum->user->name}}</a></small>  
                </div>
                  </td>
              </tr>
               @endforeach
            </tbody>
            </table> 
              </div>
                <div class="col-md-4"> <br>
                  </div>
                     </div>
                      <hr style="margin-top: 0;">
                       <div class="card">
                          <div class="card-header"></div>
                         <div class="card-body" style="background: rgb(90, 90, 90)"></div>
                        <div class="card-header"></div>
                      </div>
                      </div>
                   </div>
                  </div>
              </div>
          </div><br>
@endsection